[project]
name = "ni-specific-heat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dearpygui>=2.0.0",
    "fsspec>=2025.9.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "nidaqmx>=1.1.0",
    "pandas>=2.2.3",
    "pyacquisition>=0.1.5",
    "scipy>=1.15.3",
]
